### ISSUE TITLE
Add CLA checks to the following repos

### ISSUE THREAD

**Issue by abose** [phcode-dev/contributor-license-agreement#6]
CLA repository is: https://github.com/phcode-dev/contributor-license-agreement

- [x] https://github.com/phcode-dev/docs
     - [x] Verify that CLA checks and commenting errors work with mock pull request from test user
- [x] https://github.com/phcode-dev/phoenix
     - [x] Verify that CLA checks and commenting errors work with mock pull request from test user
- [x] https://github.com/phcode-dev/phoenix-fs
     - [x] Verify that CLA checks and commenting errors work with mock pull request from test user
- [x] https://github.com/phcode-dev/phcode.dev
     - [x] Verify that CLA checks and commenting errors work with mock pull request from test user

**Comment by psdhanesh7** [comment]
> CLA repository is: https://github.com/phcode-dev/contributor-license-agreement
> 
> * [x]  https://github.com/phcode-dev/docs
>   
>   * [x]  Verify that CLA checks and commenting errors work with mock pull request from test user
> * [x]  https://github.com/phcode-dev/phoenix
>   
>   * [x]  Verify that CLA checks and commenting errors work with mock pull request from test user
> * [x]  https://github.com/phcode-dev/phoenix-fs
>   
>   * [x]  Verify that CLA checks and commenting errors work with mock pull request from test user
> * [x]  https://github.com/phcode-dev/phcode.dev
>   
>   * [x]  Verify that CLA checks and commenting errors work with mock pull request from test user

>* Task 1 completed in pull request https://github.com/phcode-dev/docs/pull/29#issue-1230889272. Testing done in pull request https://github.com/phcode-dev/docs/pull/30#issue-1232567446 and verified.
>
>* Task 2 completed in pull request https://github.com/phcode-dev/phoenix/pull/434#issue-1231926953. Testing done in pull request https://github.com/phcode-dev/phoenix/pull/435#issue-1232574148 and verified.
>
>* Task 3 completed in pull request https://github.com/phcode-dev/phoenix-fs/pull/11#issue-1231944745. Testing done in pull request https://github.com/phcode-dev/phoenix-fs/pull/12#issue-1232579590.
>
>* Task 4 completed in pull request https://github.com/phcode-dev/phcode.dev/pull/2#issue-1231947303. Testing done in pull request https://github.com/phcode-dev/phcode.dev/pull/3#issue-1232584001.

All tasks completed.
